### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Sun-XH** [microsoft/SGSDI#12]
Hi,

I was trying to play with your pretrained model. However, the link is not accessible now. Could you please share with me a link to download the pretrained mode?

Best

**Comment by yuxiaoguo** [comment]
No problem. We will re-active the link of pretrained model ASAP.

**Comment by mingjiayang** [comment]
You can download the pretrained model from [releases](https://github.com/mingjiayang/SGSDI/releases).

**Comment by yuxiaoguo** [comment]
We also update the link in the README.md. Thanks for your report.

**Comment by Sun-XH** [comment]
Thanks!
